name: Update Feed

on:
  schedule:
    - cron: '0 0 1 */1 *'  # Runs at day 1 every month https://crontab.guru/#0_0_1_*/1_*
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Run the Go service
        run: go build -o blog-to-rss-parser && ./blog-to-rss-parser

      - name: Check for changes
        run: |
          git diff --exit-code feed.xml || echo "Changes detected"

      - name: Commit and push if feed.xml changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add feed.xml
          git commit -m "Update feed.xml [CI skip]" || exit 0
          git push